---
services:
  db:
    image: postgres:16-alpine
    env_file:
      - settings.env
  app:
    depends_on:
      - db
    ports:
      - "8000:8000"
    build: .
    restart: always
    env_file:
      - settings.env
    volumes:
      - .:/app
    stdin_open: true
    tty: true
