# Generated by Django 5.0 on 2024-06-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_link', models.CharField(default='OHzav', max_length=5, unique=True)),
                ('original_url', models.URLField(verbose_name='Original URL')),
            ],
        ),
    ]
