# Generated by Django 5.0 on 2024-07-05 18:20
from os.path import join
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings

with open(join(settings.BASE_DIR, 'install_sqids.sql'), 'r') as f:
    sqids_install = f.read()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Install sqids model
        migrations.RunSQL(sqids_install),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='Original URL')),
                ('shortened_link', models.CharField(max_length=7, unique=True, verbose_name='Shortened URL', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('time', models.TimeField(auto_now=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link')),
            ],
        ),
        # Set Default value field for the shoretned url to be generated from current id and to be of 7 chars long
        migrations.RunSQL(
            "ALTER TABLE links_link ALTER COLUMN shortened_link SET DEFAULT sqids.encode(array[currval('links_link_id_seq')], 7);"
        )
    ]
